# Generated by Django 5.0.3 on 2024-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="foods")),
                ("fast_food", models.CharField(max_length=100)),
                ("contents", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("delivery_fee", models.IntegerField()),
                ("delivery_time", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Junks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("junk_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="junks")),
                ("rating", models.IntegerField()),
                ("delivery_fee", models.IntegerField()),
                ("delivery_time", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
