# Generated by Django 5.0.3 on 2024-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "savvyfoods",
            "0002_restaurant_rename_delivery_fee_foods_deliveryfee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="location",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
