# Generated by Django 5.0.3 on 2024-04-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0003_restaurant_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foods",
            old_name="description",
            new_name="availability",
        ),
        migrations.RemoveField(
            model_name="foods",
            name="fastfood",
        ),
    ]
